language: python
cache: pip
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # this allows 'v1.2.3' like tags to be build
sudo: false
matrix:    
    fast_finish: true
    include:
        - python: 3.6
          env: TOXENV=docs
        - python: 3.6
          env: TOXENV=py36
before_install:
  - git remote set-branches origin master && git fetch
install: pip install tox tox-env
script: 
  - tox -e $TOXENV
